### DISCUSSION TITLE
Setting up Amazon ACK controller

### DISCUSSION THREAD

**Discussion by dpc** [rustshop/rustshop#7] [Technical discussion]
`kops` bootstrapped cluster seems to enable and configure OIDC if oidc store was configured (which `rustship bootstrap cluster` will.

From https://kops.sigs.k8s.io/addons/#pod-identity-webhook , run `kops edit cluster` and add:

```yaml
spec:
  certManager:
    enabled: true
  podIdentityWebhook:
    enabled: true
```

Installing particular controllers is described in https://aws-controllers-k8s.github.io/community/docs/tutorials/rds-example/#install-the-ack-service-controller-for-rds
